/*
 * Dog - Plugwise Network Driver
 * 
 * Copyright 2016 Dario Bonino 
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License
 */
package org.doggateway.drivers.plugwise.mqtt.network.messages;

/**
 * A class representing the energy state message generated by Plugwise-2-py over MQTT
 * @author <a href="mailto:dario.bonino@gmail.com">Dario Bonino</a>
 *
 */
public class EnergyStateMessage extends PowerStateMessage
{
	/*
	 * {"typ":"pwenergy","ts":1405450200,"mac":"000D6F0001nnnnnn","power":214.2069,"energy":35.7012,"interval":10}
	 */
	private double energy;
	private int interval;
	private double cum_energy;

	/**
	 * 
	 */
	public EnergyStateMessage()
	{
		// TODO Auto-generated constructor stub
	}

	/**
	 * @return the energy
	 */
	public double getEnergy()
	{
		return energy;
	}

	/**
	 * @param energy the energy to set
	 */
	public void setEnergy(double energy)
	{
		this.energy = energy;
	}

	/**
	 * @return the interval
	 */
	public int getInterval()
	{
		return interval;
	}

	/**
	 * @return the cum_energy
	 */
	public double getCum_energy()
	{
		return cum_energy;
	}

	/**
	 * @param cum_energy the cum_energy to set
	 */
	public void setCum_energy(double cum_energy)
	{
		this.cum_energy = cum_energy;
	}

	/**
	 * @param interval the interval to set
	 */
	public void setInterval(int interval)
	{
		this.interval = interval;
	}

}
