package org.doggateway.drivers.plugwise.mqtt.network.messages;

/**
 * A class representing the autonomous power state message generated by Plugwise-2-py over MQTT
 * @author <a href="mailto:dario.bonino@gmail.com">Dario Bonino</a>
 *
 */
public class PowerStateMessage extends PlugwiseMQTTMessage
{
	/*
	 * {
	 * 	"typ":"pwpower",
	 * 	"ts":1405452425,
	 * 	"mac":"000D6F0001Annnnn",
	 * 	"power":9.78}
	 */
	
	protected String typ;
	protected long ts;
	protected String mac;
	protected double power;
	/**
	 * 
	 */
	public PowerStateMessage()
	{
		super();
	}
	/**
	 * @return the typ
	 */
	public String getTyp()
	{
		return typ;
	}
	/**
	 * @param typ the typ to set
	 */
	public void setTyp(String typ)
	{
		this.typ = typ;
	}
	/**
	 * @return the ts
	 */
	public long getTs()
	{
		return ts;
	}
	/**
	 * @param ts the ts to set
	 */
	public void setTs(long ts)
	{
		this.ts = ts;
	}
	
	/**
	 * @return the power
	 */
	public double getPower()
	{
		return power;
	}
	/**
	 * @param power the power to set
	 */
	public void setPower(double power)
	{
		this.power = power;
	}
	
	
}
